import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-100 text-gray-900">
        <header className="bg-green-600 text-white p-4 text-xl font-semibold">
          🌱 EcoAir – Smart AQI Dashboard
        </header>

        <main className="p-6 max-w-6xl mx-auto">
          {children}
        </main>

        <footer className="text-center text-sm text-gray-500 mt-10">
          © 2026 EcoAir Project
        </footer>
      </body>
    </html>
  );
}